### PR TITLE
Setup basic functions in the adapter using meshkit and meshery adapter library

### LINKED ISSUE #58: Create beta adapter for Traefik Mesh
**Enhancement Description**
Use MeshKit and Meshery Adapter Library architecture to do so.

### PR DESCRIPTION
**Pull request by utkarsh-pro**
**Description**
This PR adds support for the following functions to the adapter:
1. Installing and uninstalling traefik mesh
2. Installing and uninstalling sample applications
3. Running SMI Test
4. Applying custom operations

This PR fixes https://github.com/layer5io/meshery/issues/248 and fixes #58 

Tests done:
- Installing and Uninstalling the traefik mesh
  - [x] Within the container - Working
  - [x] Outside the container -Working
- Installing and uninstalling sample applications
  - [x] Within the container - Working
  - [x] Outside the container - Working
- Running SMI Test
  - [x] Within the container - Working
  - [x] Outside the container - Working
- Apply Custom operations
  - [x] Within the container - Working
  - [x] Outside the container - Working
 
**Not For Reviewers**

### CODE REVIEW

**Comment by leecalcote** [comment]
I will make a release of the Meshery-adapter-library...

**Comment by utkarsh-pro** [comment]
@leecalcote, SMI Conformance is working now.

**Comment by leecalcote** [comment]
Very good

**Review by leecalcote — APPROVED** [review]
Lgtm. We will need to update the name of the adapter. Ithis new aha recently undergone a name change.

**Pull request merged**
